### ISSUE TITLE
Possible improvements 

### ISSUE THREAD

**Issue by ckourounis** [simeydotme/jQuery-canvas-sparkles#1]
I am a fellow frontend web developer and I noticed your jQuery-canvas-sparkles on Github. I was wondering if you could answer a few questions about it as I am hoping to include it on my website.

I notice that to view the shimmer, you need to hover over the object. Is it possible to have it start once the page loads?

Also, my site is responsive but when I shrink or expand the browser, the shimmering does not follow. So the website would be responsive but there is still a horizontal scroll bar for the leftover sparkles.

Any help is greatly appreciated.

**Comment by simeydotme** [comment]
hey @ckourounis  - i added in the ability to control it with events now... so grab the [latest files (1.0.1)](https://github.com/simeydotme/jQuery-canvas-sparkles/tree/v1.0.1) and check [the "events" section](https://github.com/simeydotme/jQuery-canvas-sparkles/blob/master/README.md#events) in the readme. :smile: 

This code below _should_ accomplish what you want, tweak it to your needs.

``` js
var sparkleTimer,
    $header = $("header")
    .sparkle({ count: 100, speed: 1.5 })
    .off("mouseover.sparkle mouseout.sparkle focus.sparkle blur.sparkle")
    .trigger("start.sparkle");

$(window).on("resize", function(){
    clearTimeout(sparkleTimer);
    sparkleTimer = setTimeout(function(){
    $header.trigger("resize.sparkle");
    },200);
});
```

and `$("header")` should be which ever element you want to sparkle :)
