### ISSUE TITLE
new to js. have some questions

### ISSUE THREAD

**Issue by Rhinoceross29** [simeydotme/jQuery-canvas-sparkles#14]
So I'm very new to js. Honestly though these jquery sparkles are amazing and after I implement them into my website ill be done with my site.  Can you just let me know what I might be missing/doing wrong??…

So I copied your "jquery-canvas-sparkles.js" onto a blank js page and then linked that and my "jquery.js" file to a html page using "<script src=""></script>". Now this is where it gets confusing to me. Would you be able to tell me what to do at this point? Basically I just want all of my "h1" tags to have some sort of continuous sparkle effect, not just on hover but when the page loads. I mean do I make a new js page and put the coding in there or do I put my code into your "jquery-canvas-sparkles.js" file? And how do I even code that? 

Hope I'm not asking too much and thanks in advance!

**Comment by simeydotme** [comment]
hi @Rhinoceross29 :)

This is the issue tracker for problems/features of the code, it is not a support forum.

- If you're having difficulty with learning web development then I'd suggest taking a nice online course from something like [Treehouse](https://teamtreehouse.com/tracks/front-end-web-development). 
- If you've got a specific problem which you can describe then I'd suggest asking for help on [Stackoverflow](www.stackoverflow.com).

Happy New Year!
