### ISSUE TITLE
Sparkles not displaying on TR element correctly

### ISSUE THREAD

**Issue by rwilkin** [simeydotme/jQuery-canvas-sparkles#15]
Hi, 
Not sure if this project is dead or not now, but, just in case it isn't....

I'm trying to get the sparkles to appear on an entire row in a table. Whenever I put the sparkles on a <tr> element it seems to shift the sparkle canvas up halfway. I've attached a screenshot of what I'm talking about.

I've tried attaching it to every <tr> element, to a class on a specific <tr> and giving the <tr> an id an attaching the sparkles to that but it always does the same thing. 

If I attach the sparkles to a <td> element it works fine but it only sparkles in that <td> element and not the adjacent <td> elements (which is expected)

Is this a bug? or am I just missing something?

![tr sparkles](https://user-images.githubusercontent.com/2383433/55621834-19b86c00-578e-11e9-97b4-21a0562d5c04.png)

**Comment by simeydotme** [comment]
Uhh,  thanks @rwilkin for the attention :) 

I'll start by saying that in the `html` specification there's only a single element that can exist inside of a `<tr>` -- which is a `<td>` -- and so it's not really feasible for a `<canvas>` to sit in/over a `<tr>` ... 

My suggestion would be to create a static sparkle box, positioned absolutely, and the same size as your table-row (you can do this with JS) and hide it using CSS ... then write a little custom event-handler for hovering the table-cells, which will position, and show, the static sparkle box where needed.

I don't know your proficiency in JS/CSS... but if what I've described is not in your skills, then you could ask on StackOverflow, or get a skilled developer to help :)

Again, thanks for the interest and apologies that this is not simply a bug.
Best, Simon.
