### ISSUE TITLE
Safari: Sparkles Error

### ISSUE THREAD

**Issue by Phenie** [simeydotme/jQuery-canvas-sparkles#3]
In Safari, the plugin causes an error as follows:
TypeError: 'undefined' is not a function (evaluating 'window.cancelAnimationFrame(this.anim)')

I don't work in Safari much, but it seems the window animation options seem to have an issue. Not sure if there is an easy work around for this or what is causing it.

EDIT: Noticing the test site worked in Safari, I see that adding 'requestAnimationFrame.js' fixes the problem!

**Comment by simeydotme** [comment]
yep, I think I do note in the README that for some browsers you may require the `requestAnimationFrame.js` polyfill...  however it's not very clear, perhaps I'll expand upon that! :) thank you for contributing! :smile:
