### ISSUE TITLE
Can't change colors?

### ISSUE THREAD

**Issue by arothmanmusic** [simeydotme/jQuery-canvas-sparkles#6]
Hi there! I'm able to alter all other parameters when implementing this script, but no matter what I do the sparkles are always white. Am I doing something wrong with my implementation? It seems to match the examples, and my changes to all other params take effect, but the color is white every time.

```
$("#glasshex").sparkle({
    color: ["#FF0000","#00FF00","#0000FF"],
    count: 90,
    overlap: 0,
    speed: 1,
    minSize: 4,
    maxSize: 7,
    direction: "both"
});
```

**Comment by simeydotme** [comment]
Please refer to: https://jsfiddle.net/h911uc7x/1/ , I copied your JS Code... I don't know what is happening with your CSS/HTML and any other JS you are running, though 

:)

**Comment by arothmanmusic** [comment]
Hi Simon!

I'll check it out. It seems to be getting the colors in other browsers but
not Chrome. May be a caching issue on my side or something. Thanks for the
reply and for the great little script!

Happy thanksgiving,
Drew
