### ISSUE TITLE
Wrap in an IIFE?

### ISSUE THREAD

**Issue by andrewtanner1987** [simeydotme/jQuery-canvas-sparkles#9]
Hi,

I just spent some time trying to get this plugin working but failed. I then discovered that the plugin is not wrapped in an IIFE (Immediately-invoked Function Expression) and subsequently does not have jQuery passed into it to preserve the use of the $ alias. This should be common plugin practise according to the jQuery learning centre (https://learn.jquery.com/plugins/basic-plugin-creation/#protecting-the-alias-and-adding-scope). Your current implementation means users are forced to wrap the function call in a ready/load handler. Amending to an IIFE removes this dependancy.

**Comment by simeydotme** [comment]
Sure, sounds good... do you want to submit a pull-request? 😃

**Comment by simeydotme** [comment]
fixed by #10
